### ISSUE TITLE
Error while fetching all custom tags in django-taggit

### ISSUE THREAD

**Issue by somghosh** [alex/django-taggit#326]
I have followed the following links to make a custom tag in django-taggit
http://django-taggit.readthedocs.org/en/latest/custom_tagging.html and https://www.neutrondrive.com/blog/multiple-tags

I am using two TaggleManagers() in the same model (BaseReward)

	class LocationTag(TagBase):
	    pass

	class LocationTaggedItem (GenericTaggedItemBase):
	  tag = models.ForeignKey(LocationTag)

	class BaseReward(models.Model):
	    location_tags = TaggableManager(through=LocationTaggedItem, related_name="reward_set", verbose_name="Location Tags", blank=True)
	    tags = TaggableManager(blank=True)
		
## Fetching tags for object.tag

    In[10]: basereward.tags.set('abc')
    In[11]: basereward.tags.all()
    Out[11]: [<Tag: abc>]

## but fetching tags for location_tags gives error

    In[12]: basereward.location_tags.set('newcity')
    In[13]: basereward.location_tags.all()
    Traceback (most recent call last):
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2883, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-13-49dcef8d54e9>", line 1, in <module>
        basereward.location_tags.all()
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 133, in all
        return self.get_queryset()
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/taggit/managers.py", line 109, in get_queryset
        return self.through.tags_for(self.model, self.instance, **kwargs)
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/taggit/models.py", line 194, in tags_for
        return cls.tag_model().objects.filter(**kwargs).distinct()
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 163, in filter
        return self.get_queryset().filter(*args, **kwargs)
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/query.py", line 593, in filter
        return self._filter_or_exclude(False, *args, **kwargs)
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/query.py", line 611, in _filter_or_exclude
        clone.query.add_q(Q(*args, **kwargs))
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1204, in add_q
        clause = self._add_q(where_part, used_aliases)
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1240, in _add_q
        current_negated=current_negated)
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1103, in build_filter
        allow_explicit_fk=True)
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1363, in setup_joins
        names, opts, allow_many, allow_explicit_fk)
      File "/Users/somghosh/voltbe2/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1283, in names_to_path
        "Choices are: %s" % (name, ", ".join(available)))
    FieldError: Cannot resolve keyword u'None' into field. Choices are: basereward, id, locationtaggeditem, name, slug

**Comment by antoniablair** [comment]
I ran into this issue recently and it was because there wasn't a related_name field on my TaggedObject(GenericTaggedItemBase) class.  

Something like this should work: 

class LocationTaggedItem(GenericTaggedItemBase):
    tag = models.ForeignKey(LocationTag, related_name="%(app_label)s_%(class)s_items")

**Comment by rtpg** [comment]
similar to #189 , we need to have better error handling for missing related names

**Comment by shifenhutu** [comment]
> I ran into this issue recently and it was because there wasn't a related_name field on my TaggedObject(GenericTaggedItemBase) class.
> 
> Something like this should work:
> 
> class LocationTaggedItem(GenericTaggedItemBase):
>     tag = models.ForeignKey(LocationTag, related_name="%(app_label)s_%(class)s_items")

its works for me



here is my code,will throw an error: 
**Cannot resolve keyword 'None' into field. Choices are: id, name, slug, wallet, a_taggeditem**

```
class a_标签(TagBase):
    class Meta:
        verbose_name = "a-tag"


class a_TaggedItem(GenericTaggedItemBase):
    tag = models.ForeignKey(a_标签, on_delete=models.CASCADE) # no set related_name



class Wallet(models.Model):
    ...
    a标签 = TaggableManager(blank=True, through=a_TaggedItem, verbose_name="a标签")
```

-------


here is my code , its works for me,
just add `related_name` to `a_TaggedItem`, like this:


```
class a_标签(TagBase):
    class Meta:
        verbose_name = "a-tag"


class a_TaggedItem(GenericTaggedItemBase):
    tag = models.ForeignKey(a_标签, on_delete=models.CASCADE, related_name="%(app_label)s_%(class)s_items") 



class Wallet(models.Model):
    ...
    a标签 = TaggableManager(blank=True, through=a_TaggedItem, verbose_name="a标签")
```
