### ISSUE TITLE
migrating from django 1.2 -> 1.6

### ISSUE THREAD

**Issue by dPeS** [alex/django-taggit#403]
I got this on taggit 0.9.3:

File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/taggit/managers.py", line 47, in **init**
    self.unique = False
AttributeError: can't set attribute

but I want to preserve ability to set non unique tag names, is there a way?

**Comment by frewsxcv** [comment]
The latest version of taggit is 0.18.2. I strongly recommend upgrading, it might fix your issue.

**Comment by dPeS** [comment]
I just tried: on .0.18.2 my e2e are failing because 2 separate users fail on adding the same tag "abc1" to 2 different objects, my models bellow:

class UserTag(TagBase):
    user = models.ForeignKey('MyUser', null=True)

class TaggsIntermediate(GenericTaggedItemBase):
    tag = models.ForeignKey(UserTag, related_name="tagged_items")

that was working on 0.9.3

**Comment by frewsxcv** [comment]
What's the exact operation you're performing and what error are you receiving?

**Comment by dPeS** [comment]
WHEN:
tag, status = UserTag.objects.get_or_create(name="abc1", user = User.objects.get(id=request.user.id))
THEN:

ERROR|2016-05-22 08:15:14,461|django.request>> Internal Server Error: /hdesk/tickets/2/add_tag/
Traceback (most recent call last):
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pepto/playground/test_hdesk/hdesk/views/ajax.py", line 66, in add_user_tag
    user = User.objects.get(id=request.user.id) )
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get_or_create
    six.reraise(*exc_info)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/taggit/models.py", line 86, in save
    return super(TagBase, self).save(*args, **kwargs)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/pepto/.virtualenvs/hdesk/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: hdesk_usertag.name

on pip: 
django-taggit (0.18.3)
Django (1.6.11)

**Comment by dPeS** [comment]
can I provide any more helpful info here?

**Comment by frewsxcv** [comment]
I'm not sure. I'm pretty busy so I unfortunately can't look into it.

**Comment by auvipy** [comment]
try update your django to 1.8

**Comment by auvipy** [comment]
this is not related to django-taggit itself hence should be closed
