### ISSUE TITLE
Can't save with django master

### ISSUE THREAD

**Issue by jpic** [alex/django-taggit#406]
When trying to save using the [test_taggit](https://github.com/jpic/test_taggit) project:

```
Internal Server Error: /admin/testapp/food/add/
Traceback (most recent call last):
  File "/home/jpic/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jpic/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/jpic/env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/jpic/env/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/home/jpic/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1370, in changeform_view
    if form.is_valid():
  File "/home/jpic/env/lib/python2.7/site-packages/django/forms/forms.py", line 161, in is_valid
    return self.is_bound and not self.errors
  File "/home/jpic/env/lib/python2.7/site-packages/django/forms/forms.py", line 153, in errors
    self.full_clean()
  File "/home/jpic/env/lib/python2.7/site-packages/django/forms/forms.py", line 364, in full_clean
    self._post_clean()
  File "/home/jpic/env/lib/python2.7/site-packages/django/forms/models.py", line 380, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, exclude)
  File "/home/jpic/env/lib/python2.7/site-packages/django/forms/models.py", line 60, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "/home/jpic/env/src/taggit/taggit/managers.py", line 438, in save_form_data
    getattr(instance, self.name).set(*value)
AttributeError: 'NoneType' object has no attribute 'set'
```

**Comment by jpic** [comment]
My bad, it's working on master, keep up the great work :guitar:
