### ISSUE TITLE
django 2.0 'TaggableRel' object has no attribute 'related_query_name'

### ISSUE THREAD

**Issue by collinanderson** [alex/django-taggit#497]
`./manage.py migrate` seems to crash since https://github.com/django/django/commit/9f4e0fde0a25ae0c21359f5194435aaf5ca341c7

```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 348, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 280, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 327, in execute
    output = self.handle(*args, **options)
  File "django/core/management/commands/migrate.py", line 160, in handle
    pre_migrate_apps = pre_migrate_state.apps
  File "django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "django/db/migrations/state.py", line 210, in apps
    return StateApps(self.real_apps, self.models)
  File "django/db/migrations/state.py", line 275, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "django/db/migrations/state.py", line 310, in render_multiple
    model.render(self)
  File "django/db/migrations/state.py", line 572, in render
    body = {name: field.clone() for name, field in self.fields}
  File "django/db/migrations/state.py", line 572, in <dictcomp>
    body = {name: field.clone() for name, field in self.fields}
  File "django/db/models/fields/__init__.py", line 468, in clone
    name, path, args, kwargs = self.deconstruct()
  File "taggit/managers.py", line 410, in deconstruct
    name, path, args, kwargs = super(TaggableManager, self).deconstruct()
  File "django/db/models/fields/related.py", line 327, in deconstruct
    if self.remote_field.related_query_name is not None:
AttributeError: 'TaggableRel' object has no attribute 'related_query_name'
```

**Comment by collinanderson** [comment]
Adding `related_query_name = None` to TaggableRel seems to fix it, though I'm not sure if that should be set to something better.

**Comment by george-silva** [comment]
Can we get a PR so we can merge? I'm not sure how active ir PR review in this repo, but this breaks django 2.0.

**Comment by collinanderson** [comment]
@george-silva Check out PR #509

**Comment by kiven517** [comment]
EVN: Django 2.0
I just installed taggit today with PIP, which still has this problem. Is this BUG not fixed yet?

**Comment by george-silva** [comment]
@kiven517 check the PR @collinanderson mentioned. the travis ci jobs are failing. Someone must be juggling time to make it happen.

**Comment by anuj9196** [comment]
I'm too having the same issue. How long it will take to fix it. I think it should be fixed on urgent basis as it is not allowing to even use the plugin on Django 2.0

**Comment by kiven517** [comment]
ENV: Django 2.0
taggit 0.22.1

I was using taggit when I was using it today, and I made a mistake in querying the tag field. I don't know if it's a compatibility issue with Django 2.0. But it's okay to query another field.
I expect them to solve the problem of taggit on Django 2.0 as soon as possible.

**Comment by goutomroy** [comment]
How to fix this issue ? I am having the problem too with Django==2.0

**Comment by arundhyani** [comment]
I am having this issue in 2.2 also and I also checked that related_query_name is set to none in __init__ but still this issue is coming .

**Comment by someshkandukuri** [comment]
'TaggableRel' object has no attribute 'related_query_name'  for 2.2.26
